"""Add packout domain tables

Revision ID: 363ad6f0697d
Revises: 67b64c6b7e88
Create Date: 2025-12-11 20:32:22.292345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '363ad6f0697d'
down_revision = '67b64c6b7e88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_analysis_cache_expires_at', table_name='photo_analysis_cache')
    op.drop_index('ix_photo_analysis_cache_id', table_name='photo_analysis_cache')
    op.drop_index('ix_photo_analysis_cache_key', table_name='photo_analysis_cache')
    op.drop_index('ix_photo_analysis_cache_user_id', table_name='photo_analysis_cache')
    op.drop_table('photo_analysis_cache')
    op.alter_column('estimates', 'adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('estimates', 'adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.create_table('photo_analysis_cache',
    sa.Column('cache_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('photo_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('analysis_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='photo_analysis_cache_pkey'),
    sa.UniqueConstraint('cache_key', name='photo_analysis_cache_cache_key_key')
    )
    op.create_index('ix_photo_analysis_cache_user_id', 'photo_analysis_cache', ['user_id'], unique=False)
    op.create_index('ix_photo_analysis_cache_key', 'photo_analysis_cache', ['cache_key'], unique=True)
    op.create_index('ix_photo_analysis_cache_id', 'photo_analysis_cache', ['id'], unique=False)
    op.create_index('ix_photo_analysis_cache_expires_at', 'photo_analysis_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###
