"""auto_sync_schema

Revision ID: 5fbe050fb10a
Revises: b662310f1380
Create Date: 2025-11-22 00:21:37.995866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbe050fb10a'
down_revision = 'b662310f1380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wm_photos_captured_date', 'wm_photos', ['captured_date'], unique=False)
    op.create_index('ix_wm_photos_category', 'wm_photos', ['category'], unique=False)
    op.create_index('ix_wm_photos_job_trashed', 'wm_photos', ['job_id', 'is_trashed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wm_photos_job_trashed', table_name='wm_photos')
    op.drop_index('ix_wm_photos_category', table_name='wm_photos')
    op.drop_index('ix_wm_photos_captured_date', table_name='wm_photos')
    # ### end Alembic commands ###
