"""Apply recent schema changes

Revision ID: b662310f1380
Revises: a377b4ba5d8f
Create Date: 2025-11-07 00:03:39.375784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b662310f1380'
down_revision = 'a377b4ba5d8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check if templates table exists before creating
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
        "WHERE table_name = 'templates')"
    ))
    templates_exists = result.scalar()
    
    if not templates_exists:
        op.create_table('templates',
            sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
            sa.Column('company_id', sa.UUID(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('type', sa.String(length=50), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('usage_count', sa.Integer(), nullable=True),
            sa.Column('created_by', sa.UUID(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.ForeignKeyConstraint(['created_by'], ['staff.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table('template_usage_log',
            sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
            sa.Column('template_id', sa.UUID(), nullable=False),
            sa.Column('used_by', sa.UUID(), nullable=True),
            sa.Column('report_id', sa.UUID(), nullable=True),
            sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
            sa.ForeignKeyConstraint(['used_by'], ['staff.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # Drop dependent tables first (wm_photo_tags depends on photo_tags)
    # Use IF EXISTS to avoid errors if already dropped
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_wm_photo_tags_photo"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_wm_photo_tags_tag"))
    conn.execute(sa.text("DROP TABLE IF EXISTS wm_photo_tags CASCADE"))

    # Now safe to drop photo_tags
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_photo_tags_client"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_photo_tags_id"))
    conn.execute(sa.text("DROP TABLE IF EXISTS photo_tags CASCADE"))

    # Drop pricing_rules
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_pricing_rules_id"))
    conn.execute(sa.text("DROP TABLE IF EXISTS pricing_rules CASCADE"))
    op.alter_column('estimate_items', 'taxable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Whether the item is subject to tax',
               existing_nullable=True)
    op.drop_index('idx_estimate_items_item_code', table_name='estimate_items')
    op.drop_index('idx_estimate_items_taxable', table_name='estimate_items', postgresql_where='(taxable = true)')
    op.drop_column('estimate_items', 'item_code')
    op.alter_column('estimates', 'estimate_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('estimates', 'op_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               nullable=True,
               comment=None,
               existing_comment='Overhead & Profit percentage')
    op.alter_column('estimates', 'op_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               nullable=True,
               comment=None,
               existing_comment='Overhead & Profit amount calculated from percentage')
    op.alter_column('estimates', 'tax_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment=None,
               existing_comment="'percentage' or 'specific' - how tax is calculated",
               existing_nullable=True)
    op.drop_index('idx_estimates_client_city', table_name='estimates')
    op.drop_index('idx_estimates_client_state', table_name='estimates')
    op.drop_index('idx_estimates_client_zipcode', table_name='estimates')
    op.drop_index('idx_estimates_estimate_type', table_name='estimates')
    op.drop_index('idx_estimates_loss_date', table_name='estimates')
    op.alter_column('invoice_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invoice_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('invoice_items', 'taxable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoice_items', 'primary_group',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Section name for organizing invoice items',
               existing_nullable=True)
    op.alter_column('invoice_items', 'secondary_group',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Sub-category within section (optional)',
               existing_nullable=True)
    op.alter_column('invoice_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Sort order within section',
               existing_nullable=True)
    op.drop_index('ix_invoice_items_primary_group', table_name='invoice_items')
    op.drop_index('ix_invoice_items_sort_order', table_name='invoice_items')
    op.alter_column('invoices', 'op_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'tax_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'payments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'show_payment_dates',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'has_receipt',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_invoices_client_company_id', table_name='invoices')
    op.drop_index('idx_invoices_has_receipt', table_name='invoices')
    op.alter_column('line_item_note_mappings', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('line_item_note_mappings', 'line_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('line_item_note_mappings', 'note_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('line_item_note_mappings', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_line_item_note_mappings_line_item', table_name='line_item_note_mappings')
    op.drop_index('idx_line_item_note_mappings_note', table_name='line_item_note_mappings')
    op.drop_constraint('line_item_note_mappings_line_item_id_note_id_key', 'line_item_note_mappings', type_='unique')
    op.alter_column('line_item_notes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('line_item_notes', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('line_item_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_line_item_notes_category', table_name='line_item_notes', postgresql_where='(category IS NOT NULL)')
    op.drop_index('idx_line_item_notes_company_id', table_name='line_item_notes', postgresql_where='(company_id IS NOT NULL)')
    op.create_index(op.f('ix_line_item_notes_id'), 'line_item_notes', ['id'], unique=False)
    op.create_foreign_key(None, 'line_item_notes', 'companies', ['company_id'], ['id'])
    op.alter_column('line_item_templates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('line_item_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('line_item_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_line_item_templates_category', table_name='line_item_templates', postgresql_where='(category IS NOT NULL)')
    op.drop_index('idx_line_item_templates_company_id', table_name='line_item_templates', postgresql_where='(company_id IS NOT NULL)')
    op.drop_index('idx_line_item_templates_is_active', table_name='line_item_templates')
    op.create_index(op.f('ix_line_item_templates_id'), 'line_item_templates', ['id'], unique=False)
    op.create_foreign_key(None, 'line_item_templates', 'companies', ['company_id'], ['id'])
    op.alter_column('line_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('line_items', 'type',
               existing_type=postgresql.ENUM('XACTIMATE', 'CUSTOM', name='lineitemtype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('line_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('line_items', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('line_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_line_items_company_id', table_name='line_items', postgresql_where='(company_id IS NOT NULL)')
    op.drop_index('idx_line_items_description_trgm', table_name='line_items', postgresql_using='gin')
    op.create_index('idx_line_items_company_active', 'line_items', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_line_items_id'), 'line_items', ['id'], unique=False)
    op.drop_constraint('fk_line_item_category', 'line_items', type_='foreignkey')
    op.create_foreign_key(None, 'line_items', 'companies', ['company_id'], ['id'])
    # Drop GIN index before altering JSONB column type
    op.drop_index('idx_template_line_items_embedded_item_code', table_name='template_line_items', postgresql_using='gin')
    op.drop_index('idx_template_line_items_line_item', table_name='template_line_items')
    op.drop_index('idx_template_line_items_template', table_name='template_line_items')

    op.alter_column('template_line_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('template_line_items', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('template_line_items', 'embedded_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Embedded item data for templates that do not reference line_items table. Structure: {"item_code": "RDG", "description": "Item name", "unit": "EA", "rate": 100.0}',
               existing_nullable=True)
    op.alter_column('template_line_items', 'quantity_multiplier',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('template_line_items', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('water_mitigation_jobs', 'property_city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City name',
               existing_nullable=True)
    op.alter_column('water_mitigation_jobs', 'property_state',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='State/Province code',
               existing_nullable=True)
    op.alter_column('water_mitigation_jobs', 'property_zipcode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Postal/ZIP code',
               existing_nullable=True)
    op.drop_index('ix_wm_jobs_property_state', table_name='water_mitigation_jobs')
    op.drop_index('ix_wm_jobs_property_street', table_name='water_mitigation_jobs')
    op.drop_index('ix_wm_jobs_property_zipcode', table_name='water_mitigation_jobs')
    op.drop_index('ix_wm_documents_active', table_name='wm_documents')
    op.alter_column('wm_photos', 'storage_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('wm_photos', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('wm_photos', 'is_trashed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_wm_photos_storage_file_id', table_name='wm_photos')
    op.drop_index('ix_wm_photos_storage_provider', table_name='wm_photos')
    op.alter_column('wm_report_configs', 'cover_title',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=True)
    op.alter_column('wm_report_configs', 'sections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wm_report_configs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wm_report_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wm_report_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_wm_report_configs_id'), 'wm_report_configs', ['id'], unique=False)
    op.drop_column('wm_report_configs', 'notes')
    op.alter_column('work_orders', 'insurance_claim_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Insurance claim number for the work order',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_policy_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Insurance policy number of the client',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_company',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Name of the insurance company',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_deductible',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Insurance deductible amount',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Name of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Email address of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_phone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Phone number of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_date_of_loss',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date when the loss occurred',
               existing_nullable=True)
    op.drop_index('ix_work_orders_insurance_claim_number', table_name='work_orders')
    op.drop_index('ix_work_orders_insurance_policy_number', table_name='work_orders')
    op.drop_table_comment(
        'xactimate_categories',
        existing_comment='Xactimate category master data',
        schema=None
    )
    op.alter_column('xactimate_components', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_components', 'direct_yield',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_components', 'spt_event_percent',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_components', 'yield_value',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_components', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.drop_table_comment(
        'xactimate_components',
        existing_comment='Detailed component breakdown for xactimate items',
        schema=None
    )
    op.alter_column('xactimate_items', 'labor_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'material_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'equipment_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'labor_burden',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'market_conditions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'untaxed_unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('xactimate_items', 'has_life_expectancy_data',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('xactimate_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_xactimate_items_description', table_name='xactimate_items')
    op.drop_index('idx_xactimate_items_item_code', table_name='xactimate_items')
    op.drop_index('idx_xactimate_items_price_date', table_name='xactimate_items')
    op.drop_index('idx_xactimate_items_unique_price', table_name='xactimate_items')
    op.drop_constraint('uk_xactimate_item_date', 'xactimate_items', type_='unique')
    op.drop_index('idx_xactimate_items_search', table_name='xactimate_items', postgresql_using='gin')
    op.create_index('idx_xactimate_items_search', 'xactimate_items', ['description'], unique=False)
    op.drop_table_comment(
        'xactimate_items',
        existing_comment='Xactimate line items with time-based pricing',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'xactimate_items',
        'Xactimate line items with time-based pricing',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_xactimate_items_search', table_name='xactimate_items')
    op.create_index('idx_xactimate_items_search', 'xactimate_items', [sa.text("to_tsvector('english'::regconfig, description)")], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uk_xactimate_item_date', 'xactimate_items', ['item_code', 'price_year', 'price_month'])
    op.create_index('idx_xactimate_items_unique_price', 'xactimate_items', ['item_code', 'price_year', 'price_month'], unique=True)
    op.create_index('idx_xactimate_items_price_date', 'xactimate_items', ['price_year', 'price_month'], unique=False)
    op.create_index('idx_xactimate_items_item_code', 'xactimate_items', ['item_code'], unique=False)
    op.create_index('idx_xactimate_items_description', 'xactimate_items', ['description'], unique=False)
    op.alter_column('xactimate_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'has_life_expectancy_data',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'untaxed_unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('xactimate_items', 'market_conditions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'labor_burden',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'equipment_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'material_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_items', 'labor_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_table_comment(
        'xactimate_components',
        'Detailed component breakdown for xactimate items',
        existing_comment=None,
        schema=None
    )
    op.alter_column('xactimate_components', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_components', 'yield_value',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_components', 'spt_event_percent',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_components', 'direct_yield',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('xactimate_components', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_table_comment(
        'xactimate_categories',
        'Xactimate category master data',
        existing_comment=None,
        schema=None
    )
    op.create_index('ix_work_orders_insurance_policy_number', 'work_orders', ['insurance_policy_number'], unique=False)
    op.create_index('ix_work_orders_insurance_claim_number', 'work_orders', ['insurance_claim_number'], unique=False)
    op.alter_column('work_orders', 'insurance_date_of_loss',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date when the loss occurred',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_phone',
               existing_type=sa.VARCHAR(length=50),
               comment='Phone number of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_email',
               existing_type=sa.VARCHAR(length=200),
               comment='Email address of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_adjuster_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Name of the insurance adjuster',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_deductible',
               existing_type=sa.VARCHAR(length=50),
               comment='Insurance deductible amount',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_company',
               existing_type=sa.VARCHAR(length=200),
               comment='Name of the insurance company',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_policy_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Insurance policy number of the client',
               existing_nullable=True)
    op.alter_column('work_orders', 'insurance_claim_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Insurance claim number for the work order',
               existing_nullable=True)
    op.add_column('wm_report_configs', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wm_report_configs_id'), table_name='wm_report_configs')
    op.alter_column('wm_report_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('wm_report_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wm_report_configs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('wm_report_configs', 'sections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('wm_report_configs', 'cover_title',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'Water Mitigation Report'::character varying"),
               existing_nullable=True)
    op.create_index('ix_wm_photos_storage_provider', 'wm_photos', ['storage_provider'], unique=False)
    op.create_index('ix_wm_photos_storage_file_id', 'wm_photos', ['storage_file_id'], unique=False)
    op.alter_column('wm_photos', 'is_trashed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('wm_photos', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=True)
    op.alter_column('wm_photos', 'storage_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=True)
    op.create_index('ix_wm_documents_active', 'wm_documents', ['is_active'], unique=False)
    op.create_index('ix_wm_jobs_property_zipcode', 'water_mitigation_jobs', ['property_zipcode'], unique=False)
    op.create_index('ix_wm_jobs_property_street', 'water_mitigation_jobs', ['property_street'], unique=False)
    op.create_index('ix_wm_jobs_property_state', 'water_mitigation_jobs', ['property_state'], unique=False)
    op.alter_column('water_mitigation_jobs', 'property_zipcode',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal/ZIP code',
               existing_nullable=True)
    op.alter_column('water_mitigation_jobs', 'property_state',
               existing_type=sa.VARCHAR(length=50),
               comment='State/Province code',
               existing_nullable=True)
    op.alter_column('water_mitigation_jobs', 'property_city',
               existing_type=sa.VARCHAR(length=100),
               comment='City name',
               existing_nullable=True)
    op.create_index('idx_template_line_items_template', 'template_line_items', ['template_id'], unique=False)
    op.create_index('idx_template_line_items_line_item', 'template_line_items', ['line_item_id'], unique=False)
    op.create_index('idx_template_line_items_embedded_item_code', 'template_line_items', [sa.text("(embedded_data -> 'item_code'::text)")], unique=False, postgresql_using='gin')
    op.alter_column('template_line_items', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('template_line_items', 'quantity_multiplier',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('template_line_items', 'embedded_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Embedded item data for templates that do not reference line_items table. Structure: {"item_code": "RDG", "description": "Item name", "unit": "EA", "rate": 100.0}',
               existing_nullable=True)
    op.alter_column('template_line_items', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('template_line_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'line_items', type_='foreignkey')
    op.create_foreign_key('fk_line_item_category', 'line_items', 'line_item_categories', ['cat'], ['code'], ondelete='SET NULL')
    op.drop_index(op.f('ix_line_items_id'), table_name='line_items')
    op.drop_index('idx_line_items_company_active', table_name='line_items')
    op.create_index('idx_line_items_description_trgm', 'line_items', ['description'], unique=False, postgresql_using='gin')
    op.create_index('idx_line_items_company_id', 'line_items', ['company_id'], unique=False, postgresql_where='(company_id IS NOT NULL)')
    op.alter_column('line_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('line_items', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('line_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('line_items', 'type',
               existing_type=postgresql.ENUM('XACTIMATE', 'CUSTOM', name='lineitemtype'),
               server_default=sa.text("'CUSTOM'::lineitemtype"),
               existing_nullable=False)
    op.alter_column('line_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'line_item_templates', type_='foreignkey')
    op.drop_index(op.f('ix_line_item_templates_id'), table_name='line_item_templates')
    op.create_index('idx_line_item_templates_is_active', 'line_item_templates', ['is_active'], unique=False)
    op.create_index('idx_line_item_templates_company_id', 'line_item_templates', ['company_id'], unique=False, postgresql_where='(company_id IS NOT NULL)')
    op.create_index('idx_line_item_templates_category', 'line_item_templates', ['category'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.alter_column('line_item_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('line_item_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('line_item_templates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'line_item_notes', type_='foreignkey')
    op.drop_index(op.f('ix_line_item_notes_id'), table_name='line_item_notes')
    op.create_index('idx_line_item_notes_company_id', 'line_item_notes', ['company_id'], unique=False, postgresql_where='(company_id IS NOT NULL)')
    op.create_index('idx_line_item_notes_category', 'line_item_notes', ['category'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.alter_column('line_item_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('line_item_notes', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('line_item_notes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_unique_constraint('line_item_note_mappings_line_item_id_note_id_key', 'line_item_note_mappings', ['line_item_id', 'note_id'])
    op.create_index('idx_line_item_note_mappings_note', 'line_item_note_mappings', ['note_id'], unique=False)
    op.create_index('idx_line_item_note_mappings_line_item', 'line_item_note_mappings', ['line_item_id'], unique=False)
    op.alter_column('line_item_note_mappings', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('line_item_note_mappings', 'note_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('line_item_note_mappings', 'line_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('line_item_note_mappings', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index('idx_invoices_has_receipt', 'invoices', ['has_receipt'], unique=False)
    op.create_index('idx_invoices_client_company_id', 'invoices', ['client_company_id'], unique=False)
    op.alter_column('invoices', 'has_receipt',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('invoices', 'show_payment_dates',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('invoices', 'payments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('invoices', 'tax_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'percentage'::character varying"),
               existing_nullable=True)
    op.alter_column('invoices', 'op_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_index('ix_invoice_items_sort_order', 'invoice_items', ['sort_order'], unique=False)
    op.create_index('ix_invoice_items_primary_group', 'invoice_items', ['primary_group'], unique=False)
    op.alter_column('invoice_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Sort order within section',
               existing_nullable=True)
    op.alter_column('invoice_items', 'secondary_group',
               existing_type=sa.VARCHAR(length=255),
               comment='Sub-category within section (optional)',
               existing_nullable=True)
    op.alter_column('invoice_items', 'primary_group',
               existing_type=sa.VARCHAR(length=255),
               comment='Section name for organizing invoice items',
               existing_nullable=True)
    op.alter_column('invoice_items', 'taxable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('invoice_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('invoice_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_estimates_loss_date', 'estimates', ['loss_date'], unique=False)
    op.create_index('idx_estimates_estimate_type', 'estimates', ['estimate_type'], unique=False)
    op.create_index('idx_estimates_client_zipcode', 'estimates', ['client_zipcode'], unique=False)
    op.create_index('idx_estimates_client_state', 'estimates', ['client_state'], unique=False)
    op.create_index('idx_estimates_client_city', 'estimates', ['client_city'], unique=False)
    op.alter_column('estimates', 'tax_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'percentage'::character varying"),
               comment="'percentage' or 'specific' - how tax is calculated",
               existing_nullable=True)
    op.alter_column('estimates', 'op_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text('0'),
               nullable=False,
               comment='Overhead & Profit amount calculated from percentage')
    op.alter_column('estimates', 'op_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               nullable=False,
               comment='Overhead & Profit percentage')
    op.alter_column('estimates', 'estimate_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'standard'::character varying"),
               nullable=True)
    op.add_column('estimate_items', sa.Column('item_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Line item selection code (Sel column from frontend)'))
    op.create_index('idx_estimate_items_taxable', 'estimate_items', ['taxable'], unique=False, postgresql_where='(taxable = true)')
    op.create_index('idx_estimate_items_item_code', 'estimate_items', ['item_code'], unique=False)
    op.alter_column('estimate_items', 'taxable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='Whether the item is subject to tax',
               existing_nullable=True)
    op.create_table('wm_photo_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('photo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tagged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tagged_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['wm_photos.id'], name='wm_photo_tags_photo_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['photo_tags.id'], name='wm_photo_tags_tag_id_fkey'),
    sa.ForeignKeyConstraint(['tagged_by_id'], ['staff.id'], name='wm_photo_tags_tagged_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wm_photo_tags_pkey')
    )
    op.create_index('ix_wm_photo_tags_tag', 'wm_photo_tags', ['tag_id'], unique=False)
    op.create_index('ix_wm_photo_tags_photo', 'wm_photo_tags', ['photo_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rule_type', postgresql.ENUM('FLAT', 'TIERED', 'LOCATION_BASED', 'ADDON', name='pricingruletype'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name='pricing_rules_document_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pricing_rules_pkey')
    )
    op.create_index('ix_pricing_rules_id', 'pricing_rules', ['id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tag_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tag_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], name='photo_tags_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_tags_pkey')
    )
    op.create_index('ix_photo_tags_id', 'photo_tags', ['id'], unique=False)
    op.create_index('ix_photo_tags_client', 'photo_tags', ['client_id'], unique=False)
    op.drop_table('template_usage_log')
    op.drop_table('templates')
    # ### end Alembic commands ###
